# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-25 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0002_movie_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, to='spa.Actor'),
        ),
    ]
